export type FeatureProduct = {
  productTitle: string;
  productDescription: string;
  mfrPartNo: string;
  isHazardous: boolean;
  isDirectlyShippedFromVendor: boolean;
  specialShipping: boolean;
  groupId: number;
  productId: string;
  slug: string;
  groupImage: string;
  productImage: string;
  productSku: string;
  unitOfMeasure: string;
  isSaleItem: boolean;
  isNewItem: boolean;
  minimumOrderQuantity: number;
  quantityByIncrements: number;
  brandId: number;
  brandName: string;
  categoryId: number;
  categoryName: string;
  subCategoryId: number;
  subCategoryName: string;
};
