import { type Metadata } from "next";
import { type ReactNode } from "react";
import Providers from "./providers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          <header></header>

          <main>{children}</main>

          <footer></footer>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
