import { type Metadata } from "next";
import dynamic from "next/dynamic";
import { type ReactNode } from "react";
import "./globals.css";
import Providers from "./providers";

const Header = dynamic(() => import("./_header"));

export const metadata: Metadata = {
  title: {
    default: "Wurth Louis and Company",
    template: "%s | Wurth Louis and Company",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />

          <main>{children}</main>

          <footer></footer>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
