import { type Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { type ReactNode } from "react";
import Header from "./_header";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: {
    default: "Wurth Louis and Company",
    template: "%s | Wurth Louis and Company",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <NextTopLoader showSpinner={false} color="#cc0000" />

        <Providers>
          <Header />

          <main>{children}</main>

          <footer></footer>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
