import { type Metadata } from "next";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import { type ReactNode } from "react";
import Footer from "./_footer";
import Header from "./_header";
import { cn } from "./_utils/helpers";
import AccountSelectorDialog from "./account-selector-dialog";
import "./globals.css";
import LoginDialog from "./login-dialog";
import Providers from "./providers";

const wurth = localFont({
  src: [
    {
      path: "./wuerth-bold.woff2",
      weight: "700",
    },
    {
      path: "./wuerth-extrabold-cond.woff2",
      weight: "800",
    },
  ],
  variable: "--wurth-font",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Wurth Louis and Company",
    template: "%s | Wurth Louis and Company",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" className={cn("h-full scroll-smooth", wurth.variable)}>
      {!!process.env.NEXT_PUBLIC_WURTH_LAC_API && (
        <head>
          {/* Preconnect to the API */}
          <link rel="preconnect" href={process.env.NEXT_PUBLIC_WURTH_LAC_API} />
        </head>
      )}

      <body className="font-arial flex h-full flex-col justify-between text-[15px] leading-5 antialiased">
        <NextTopLoader showSpinner={false} color="#cc0000" />

        <Providers>
          <Header />

          <main className="full-bleed-wrapper flex-1">{children}</main>

          <Footer />

          <LoginDialog />
          <AccountSelectorDialog />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
