export const PLANTS = {
  L002: "Salt Lake City, UT",
  L003: "Boise, ID",
  L004: "Idaho Falls, ID",
  L006: "West Jordan, UT",
  L007: "Las Vegas, NV",
  L008: "Denver, CO",
  L009: "Phoenix, AZ",
  L010: "Brea, CA",
  L011: "San Diego, CA",
  L020: "Grand Prairie, TX",
  L021: "Houston, TX",
  L022: "San Antonio, TX",
  L023: "Oklahoma City, OK",
  L024: "Baton Rouge, LA",
  L025: "Benton, AR",
  L042: "Post Falls, ID",
  L043: "Lacey, WA",
  L044: "Portland, OR",
  L050: "Anaheim, CA",
  L055: "San Marcos, CA",
  L075: "St George, UT",
} as const;

export const SHIPPING_METHODS = {
  "03": "Boise Plt Trnf",
  "04": "Idaho Falls Plt Trnf",
  "05": "Albuquerque Plt Trnf",
  "06": "West Jordan Plnt Trn",
  "07": "Las Vegas Plnt Trnf",
  "08": "Colorado Plnt Trnf",
  "09": "Arizona Plnt Trnf",
  "10": "Brea   Plnt Trnf",
  "11": "San Diego Plnt Trnf",
  "12": "Fremont Plnt Trnf",
  "16": "Sacramento Plnt Trnf",
  "1C": "UPS Next-Day Air Sav",
  "1D": "UPS Next-Day Air",
  "1S": "UPS Saturday Delv",
  "20": "Grnd Prair Plnt Trnf",
  "21": "Houston Plnt Trnf",
  "22": "San Antonio Plt Trnf",
  "23": "OKC Plant Transfer",
  "24": "BR Plant Transfer",
  "25": "Arkansas Plnt Trnsfr",
  "2A": "UPS 2-Day AM Dlv",
  "2D": "UPS 2-Day Air",
  "3D": "UPS 3-Day",
  "3W": "Boise Will Call",
  "42": "Spokane Plnt Trnf",
  "43": "Seattle Plnt Trnf",
  "44": "Portland Plnt Trnf",
  "4T": "Spokane Truck",
  "4W": "Spokane Will Call",
  "50": "Anaheim Plnt Trnf",
  "55": "San Marcos Plnt Trnf",
  "62": "SLC/WC Will Call",
  "6T": "Utah DC Truck",
  "6W": "Utah DC Will Call",
  "75": "St George Plnt Trnf",
  "7T": "Las Vegas Truck",
  "8T": "Colorado Truck",
  "8W": "Colorado Will Call",
  "9T": "Arizona Truck",
  "9W": "Arizona Will Call",
  AR: "ARS Label",
  AT: "Arkansas Turck",
  AW: "Anaheim Will Call",
  BC: "Baton Rouge Will Cal",
  BG: "Baton Rouge Truck",
  BT: "Brea DC Truck",
  BZ: "Boise Truck",
  CC: "Common Carrier",
  CO: "On Trac",
  CR: "Central",
  CS: "Courier Service",
  CX: "CONWAY/XPO/XP",
  DA: "DATS",
  DW: "Direct Will Call",
  F1: "Fed Ex - Overnight",
  F2: "Fed Ex - 2nd Day",
  F3: "Fed Ex - 3rd Day",
  FF: "Fedex Freight",
  FT: "Fremont Truck",
  FW: "Fremont Will Call",
  FX: "Fed Ex Ground",
  GS: "Golden State O/N",
  GT: "GP DC Truck",
  GW: "GP DC Will Call",
  HT: "Houston Truck",
  HW: "Houston Will Call",
  IF: "Idaho Falls Truck",
  IW: "Idaho Falls Will Cal",
  KT: "Seattle Truck",
  KW: "Seattle Will Call",
  LV: "Las Vegas Will Call",
  ML: "US Mail",
  OH: "Oak Harbor",
  OK: "OKC Truck",
  OL: "Old Dominion",
  OP: "OSR Will Call",
  OT: "Our Truck",
  OW: "OKC Will Call",
  PW: "Portland Will Call",
  RE: "R-Express",
  RN: "R&L",
  SA: "San Antonio W/Call",
  SG: "St George Will Call",
  SK: "Sacramento Truck",
  SS: "SELF-Southeastern",
  ST: "St. George Truck",
  SX: "San Marcos Truck",
  SY: "Saia LTL",
  TP: "Portland Truck",
  TS: "San Antonio Truck",
  UP: "UPS Ground",
  W1: "Will Call <1 hr",
  W2: "Will Call - PCD TUK",
  W3: "Will Call - PCD SWAN",
  W4: "Will Call - FLUX",
  W5: "Will Call Showroom",
  WA: "Arkansas Will Call",
  WB: "Brea DC Will Call",
  WI: "Will Call Immed",
  WM: "San Marcos Will Call",
  WR: "W/Call Rtn CredAppld",
  YF: "YRC-Yellow-Freight",
} as const;

export const UI_DATE_FORMAT = "MM/DD/YYYY" as const;
