name: "Chromatic"

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chromatic
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Chromatic for web-ui package
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_1 }}
          workingDir: packages/web-ui
          onlyChanged: true
          traceChanged: true
          autoAcceptChanges: true
          exitZeroOnChanges: true
          exitOnceUploaded: true
      - name: Run Chromatic for wbs-web app
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_2 }}
          workingDir: apps/wbs-web
          onlyChanged: true
          traceChanged: true
          autoAcceptChanges: true
          exitZeroOnChanges: true
          exitOnceUploaded: true
